#question_3
###(1)
wage=read.csv("wage.csv")
###(2)
# データの大きさ(不正解)

#平均値
mean(wage$wage)
#標準偏差
sd(wage$wage)
###(3)
hist(wage$wage, xlab = "wage", ylab = "相対密度", main = "Q3_3", xlim =c(0, 30) , ylim =c(0, 250), col = "white")
abline(v=median(wage$wage))
text(x=6, y=150, "中央値", col= "blue")
###(4)
boxplot(wage$wage~wage$female, xlab = "sex", ylab = "wage", main = "Q3_4", names=c("男性", "女性"), col="white", border="black")
###(5)
sex_dummy=factor(wage$female, labels = c("男性","女性"))
tapply(wage$wage, sex_dummy, median)
tapply(wage$wage, sex_dummy, mean)
###(6)
wage$female_dummy=factor(wage$female, labels=c("男性", "女性"))
wage$married_dummy=factor(wage$married, labels = c("非婚", "既婚"))
crosstab = table(wage$female_dummy, wage$married_dummy)
addmargins(prop.table(crosstab))
###(7)
addmargins(prop.table(crosstab, margin = 1))
###(8)
aaa=table(wage$married_dummy, wage$female_dummy)
mosaicplot(aaa, xlab = "marry", ylab = "sex", main = "Q3_8", color = rainbow(2))
